---

- name: Removing vm's from vSphere
  vsphere_guest:
    vcenter_hostname: kef1-vcenter-ceng.lab.rmsonecloud.net
    username: lab\svc-vmcreator
    password: O5ZkSFQ8b8gP
    guest: "{{ inventory_hostname }}"
    state: absent
    force: yes
