---

- name: Removing guests from vSphere
  vsphere_guest:
    vcenter_hostname: vcenter.domain.com
    username: username
    password: password
    guest: "{{ inventory_hostname }}"
    state: absent
    force: yes
