---

# Create a new VM on an ESX server
# Returns changed = False when the VM already exists
# Returns changed = True and a adds ansible_facts from the new VM
# State will set the power status of a guest upon creation. Use powered_on to create and boot.
# Options ['state', 'vm_extra_config', 'vm_disk', 'vm_nic', 'vm_hardware', 'esxi'] are required together

- vsphere_guest:
    vcenter_hostname: vcenter.domain.com
    username: username
    password: password
    guest: "{{ inventory_hostname }}" #get hostnames dynamically from ansible hosts file
    from_template: yes
    template_src: template_name
    esxi:
      datacenter: datacenter_name
      hostname: clusterhost_name
